#!/bin/sh

LOGFILE=.git/hooks/logs/post-merge.log

# Create logs directory if it doesn't exist
mkdir -p .git/hooks/logs

# Log the date and time of the execution
echo "=== Post-merge Hook Executed on $(date) ===" >> "$LOGFILE"

# Your commands here
echo "Running post-merge tasks..." >> "$LOGFILE" 2>&1

chmod +x ./scripts/*

./scripts/setup-server.sh >> "$LOGFILE" 2>&1

chmod reset --hard origin/main

# Log completion
echo "Post-merge hook completed." >> "$LOGFILE"
