name: Deploy Web

on:
  push:
    branches:
      - main
    paths:
      - web/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build web
        run: npm run build

      - name: Deploy web
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: web/dist/spa
          target: ~/domains/anggota.kpbi.or.id/public_html/source/www
          rm: true
          overwrite: true
          strip_components: 3

      - name: Link storage
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH=/opt/alt/php83/usr/bin:$PATH
            cd ~/domains/anggota.kpbi.or.id/public_html/source/server
            APP_PUBLIC_PATH='../www' php artisan storage:link
