name: Deploy Web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get runner credentials
        id: runner-creds
        run: |
          echo "username=$(whoami)@$(hostname -I)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          npm install
          npx -w web quasar build
          cd web/dist/spa
          zip -r dist.zip *
          mv dist.zip ../../../dist.zip
          cd ../../../
      - name: Upload artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist.zip
      - run: echo "username = ${{ steps.runner-creds.outputs.username }}\n ${{ steps.artifact.outputs.artifact-url }}"
      # - name: Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       cd ~/anggota.kpbi.or.id
      #       rm -rf *
